### ISSUE TITLE
Post method for articles endpoint requires titles and contents properties

### ISSUE THREAD

**Issue by Atlantic777** [libreoss/liberator-api#106]
If we want to post new article, we have to put both contents and titles field into the payload. This doesn't make sense because we can't add new title unless we have ID of article. The same goes for contents.

This means that now we have to send contents and titles properties set to null value. After that we get id of our fresh article and then we can post titles and contents related to it.

It is more convenient to me to accept post requests with only really required fields. That means that currently only author and state properties of an article are really required and we should accept every post request which has at least those two.

We still have to decide what's the best approach to require at least one title object when creating new article, but that's completely different issue.

**Comment by fantastic001** [comment]
When we create article with POST /articles/ we need only to provide title, not even author nor state

**Comment by Atlantic777** [comment]
Yup, but that's new issue. Let's move that discussion there: #107

**Comment by fantastic001** [comment]
Can you write example where it fails and what would you expect if it worked?

**Comment by Atlantic777** [comment]
When you open DRF API browser on http://192.168.66.6:8000/api/v1/articles, and in the bottom part of the screen switch to *raw format*, you should be able to create a new article by sending a *POST* request with *incomplete* data.

That means that the object in the *POST* should have only `authors` field required (and it's questionable is even that really a requirement).

How to reproduce:
 - Go to API browser on `articles` page
 - switch from `HTML` to `raw`
 - add valid user IDs to authors list in *POST* payload
 - delete some other not required fields
 - try to send the request
 - it fails with `missing required fields`-like error message
