### ISSUE TITLE
User listing does not work 

### ISSUE THREAD

**Issue by fantastic001** [libreoss/liberator-api#117]
When trying to authenticate and then list users via api/v1/users/ endpoint, it displays error message saying "ord() expected string of length 1, but int found"

How to reproduce: 

Assuming that superuser is admin@admin.com and its password is admin, then getting token and listing users will look like this

curl -H "Content-Type: application/json" -X POST -d '{"email": "admin@admin.com", "password": "admin"}'  "http://192.168.66.6:8000/api/v1/auth/"

curl -H "Authorization: JWT <token>" http://192.168.66.6:8000/api/v1/users/ 

Substitute <token> with given token 

Second command will output HTML content which displays above-mentioned message (try opening it in web browser if you cannot read it from cli)

**Comment by fantastic001** [comment]
When I try with basic HTTP authentication, it works

Problem is in JWT authentication

**Comment by fantastic001** [comment]
I've made falling test for this case 
https://github.com/fantastic001/liberator-api/commit/eccb9f6ee7150cb9e205dd1c49a52dc1d040ff37

**Comment by Atlantic777** [comment]
It seems that this issue doesn't exist when running in docker. Here's how to test it in docker:

- Follow instructions in https://github.com/libreoss/liberator-api/commit/0376ef48ffa3fede03b2dd623a2f56951d0437a1
- Attach shell with: `docker-compose run bash`
- Install needed packages with: `pip install django_nose factory_boy`
- Run tests: `python manage.py test`
- You should see that 34 tests pass.

This makes me think that we have some inconsistent package versions.

**Comment by Atlantic777** [comment]
And here's pip freeze of docker packages. There is obvious mismatch between vagrant and docker platforms.

```
root@ccabd1a1afe4:/code# pip freeze
Django==1.7.11
django-cors-headers==1.1.0
django-nose==1.4.2
djangorestframework==3.3.1
djangorestframework-jwt==1.7.2
drf-extensions==0.2.7
drf-nested-routers==0.11.1
factory-boy==2.6.0
fake-factory==0.5.3
nose==1.3.7
psycopg2==2.6.1
PyJWT==1.4.0
```

**Comment by Atlantic777** [comment]
The main difference I see is that in docker we use python 3.4 and in vagrant we use python 3.2. It's not so easy to prove that this is the problem because vagrant box is a custom build of Debian Wheezy which supports only python 3.2.

I recommend following ways to triage this further:
- Check if problem disappears with python 3.4. If this is true, this is one way to go -> upgrade image (vagrant box or docker image)

- Try to downgrade related packages until right combination of versions is found. Freeze it into requirements.txt

**Comment by Atlantic777** [comment]
- Upgrade to python 3.4 fixes this. Pull this commit: https://github.com/Atlantic777/liberator/commit/cae6a49e0057c147e8da1f8bfe7788467c11d253
