### ISSUE TITLE
Grammar support for authors, lectors and others.

### ISSUE THREAD

**Issue by Atlantic777** [libreoss/liberator-api#31]
A place where lectors can leave suggestions for authors and for authors to find answers to FAQ. Examples: translation, transcription...

Target groups: lectors, authors, translators.

**Comment by Atlantic777** [comment]
Diskusije o nejasnoćama.

**Comment by Atlantic777** [comment]
As bandigarf stated, we should stick to already available solutions for dicts like hunspell, aspell and others.

**Comment by mekanix** [comment]
@Atlantic777 didn't we agree on exporting this functionality to separate project?
