### ISSUE TITLE
Setup unit tests for the REST

### ISSUE THREAD

**Issue by Atlantic777** [libreoss/liberator-api#72]
We should write tests while developing the REST framework. Tests runner whould be Nose and we should have a test suite for testing CRUD REST is current milestone February REST.

Tests should probably use Django REST framework like here: http://www.django-rest-framework.org/api-guide/testing/

Check if test suites can be nested so we have test suite for every REST endpoint which can be then run at once as for testing features for current milestone.

For now, we have following REST endpoints:
- /articles/ (POST, GET)
- /articles/:id (POST, PUT, GET)
- /articles/:id/content (POST)
- /articles/:id/content/:id (GET)

Further specification will ready this weekend. Just make Nose run some example test suites for those REST endpoints and we will fill test cases after that.

**Comment by mekanix** [comment]
Done in #97
