### ISSUE TITLE
Error while trying to create new article via REST

### ISSUE THREAD

**Issue by fantastic001** [libreoss/liberator-api#86]
When i try to create new article as it is explained here https://github.com/libreoss/liberator/wiki/api_articles i get error.

=== How to reproduce problem === 

I have created test for this case https://github.com/fantastic001/liberator/commit/70a5af705432d14e31d6d49d2699a3d1b2095d3a

=== How to solve === 

There are two approaches: 

1. Simply change specification so it explains hot to do it with specifying state field 

2. Change creation methods to support creating articles without specifying state field (select some default state)

**Comment by Crawleyprint** [comment]
+1 for second approach

**Comment by mekanix** [comment]
The REST is changed in https://github.com/libreoss/liberator/pull/87. Can you give it a try again?

**Comment by mekanix** [comment]
The second approach is error prone. States are rows in ArticleState table, which is not populated at the time of deployment. We discussed this, and decided we should leave up to the team of editors/authors/admins to decide what the set of states should be. I think state should be None upon creation signalizing "created" state.

**Comment by mekanix** [comment]
Depends on #70

**Comment by mekanix** [comment]
As #70 is solved, data sent to and recieved from the server changed. See the example at [the wiki](https://github.com/libreoss/liberator/wiki/api_articles#working-example).
